server:
  allow_cors: false
  http:
    port: 8080
  grpc:
    port: 9092
  limit:
    enabled: true
    period: 86400
chains:
  - name: "landslide"
    key_name: "wasm"
    chain_id: "landslide-test"
    # rpc_endpoint: "http://127.0.0.1:9650/ext/bc/2rUgWwRguT2uAzPFTZSz2XrJiVZhif5Yv6NKGupFj89CJTEfQu/rpc"
    rpc_endpoint: "http://10.128.78.130:9650/ext/bc/2rUgWwRguT2uAzPFTZSz2XrJiVZhif5Yv6NKGupFj89CJTEfQu/rpc"
    account_prefix: "wasm"
    sender: "wasm1kng6sqkm0mjuh09cwz6u86f75lmeflj9h0fqhr"
    key: "tip yard art tape orchard universe angle flame wave gadget raven coyote crater ethics able evoke luxury predict leopard delay peanut embody blast soap"
    gas_adjustment: 2
    gas_price: "0.01stake"
    drop_coin: "1000000stake"
